name: 'PIPELINE REACT (VERCEL)'

trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: build
  jobs:
  - job:
    displayName: Iniciando dependencias
    steps:
    - task: NodeTool@0
      displayName: Instalando Node
      inputs:
        versionSource: 'spec'
        versionSpec: '6.x'
        checkLatest: true

    - script: dir
      displayName: Instalando pacotes
      


