name: 'PIPELINE REACT (VERCEL)'

trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job:
    displayName: Iniciando dependencias
    steps:
    - task: NodeTool@0
      displayName: Instalando Node
      inputs:
        versionSpec: '16.x'

    - script: npm install
      displayName: Instalando pacotes
      


