name: 'PIPELINE REACT (VERCEL)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job:
    displayName: Iniciando dependencias
    steps:
    - task: NodeTool@0
      displayName: Instalando Node
      inputs:
        versionSpec: '16.x'

    - script: npm install
      displayName: Instalando pacotes
      
    - script: npm run build
      displayName: Gerando build

    - script: npm install -g vercel 
      displayName: Instalando Vercel
    
- stage: deploy
  dependsOn: build
  jobs:
  - job: 
    displayName: Realizando o deploy no Vercel
    steps:
    - task: vercel-deployment-task@1
      displayName: Deploy para o vercel
      inputs:
        vercelProjectId: 'prj_5ZDP7WTWgzAROq6mJkVyjYc8xJuX'
        vercelOrgId: 'qKriBgs7YOxYvGuWSPhpQv4X'
        vercelToken: 'AKJ2m1t2qARHp4FE9Sv7a8Qq'
        production: true


